#!/usr/bin/env bash
#
# TarlaAnaliz Type Generator
# Generates TypeScript and Python types from JSON Schema
#
# Usage:
#   ./tools/generate_types.sh
#   ./tools/generate_types.sh --typescript
#   ./tools/generate_types.sh --python
#   ./tools/generate_types.sh --clean
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SCHEMAS_DIR="$BASE_DIR/schemas"
GENERATED_DIR="$BASE_DIR/generated"
TS_OUT="$GENERATED_DIR/typescript"
PY_OUT="$GENERATED_DIR/python"

# Logging functions
log_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

# Clean generated files
clean_generated() {
    log_info "Cleaning generated files..."
    
    if [ -d "$GENERATED_DIR" ]; then
        rm -rf "$GENERATED_DIR"
        log_success "Cleaned $GENERATED_DIR"
    else
        log_info "No generated files to clean"
    fi
}

# Setup directories
setup_directories() {
    log_info "Setting up directories..."
    
    mkdir -p "$TS_OUT"
    mkdir -p "$PY_OUT"
    
    # Create .gitignore in generated/
    cat > "$GENERATED_DIR/.gitignore" << 'EOF'
# Auto-generated files - DO NOT EDIT
# Generated by tools/generate_types.sh
*
!.gitignore
!README.md
EOF
    
    # Create README in generated/
    cat > "$GENERATED_DIR/README.md" << 'EOF'
# Generated Types

**⚠️  DO NOT EDIT THESE FILES MANUALLY**

These files are auto-generated from JSON Schema definitions.

## Regeneration

To regenerate types:

```bash
./tools/generate_types.sh
```

## TypeScript

TypeScript types are generated using `json-schema-to-typescript`.

```typescript
import { Field } from './typescript/field.v1';
import { Mission } from './typescript/mission.v1';
```

## Python

Python types are generated using `datamodel-code-generator`.

```python
from generated.python.field_v1 import Field
from generated.python.mission_v1 import Mission
```

## Notes

- Types follow source JSON Schema exactly
- All fields use PascalCase for types, camelCase for properties
- Optional fields are marked with `?` (TS) or `Optional[]` (Python)
- Enums are generated as union types (TS) or Literal types (Python)
- Generated files include JSDoc/docstrings from schema descriptions

**Last Generated:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF
    
    log_success "Directories set up"
}

# Check dependencies
check_dependencies() {
    log_info "Checking dependencies..."
    
    local missing_deps=()
    
    # TypeScript dependencies
    if ! command -v npm &> /dev/null; then
        missing_deps+=("npm")
    elif ! npm list -g json-schema-to-typescript &> /dev/null; then
        log_warning "json-schema-to-typescript not installed globally"
        log_info "Installing json-schema-to-typescript..."
        npm install -g json-schema-to-typescript || missing_deps+=("json-schema-to-typescript")
    fi
    
    # Python dependencies
    if ! command -v python3 &> /dev/null; then
        missing_deps+=("python3")
    elif ! python3 -c "import datamodel_code_generator" 2>/dev/null; then
        log_warning "datamodel-code-generator not installed"
        log_info "Installing datamodel-code-generator..."
        pip3 install datamodel-code-generator --break-system-packages || missing_deps+=("datamodel-code-generator")
    fi
    
    if [ ${#missing_deps[@]} -gt 0 ]; then
        log_error "Missing dependencies: ${missing_deps[*]}"
        log_error "Please install:"
        for dep in "${missing_deps[@]}"; do
            if [ "$dep" == "npm" ]; then
                echo "  - Node.js and npm: https://nodejs.org/"
            elif [ "$dep" == "json-schema-to-typescript" ]; then
                echo "  - npm install -g json-schema-to-typescript"
            elif [ "$dep" == "python3" ]; then
                echo "  - Python 3.8+: https://python.org/"
            elif [ "$dep" == "datamodel-code-generator" ]; then
                echo "  - pip3 install datamodel-code-generator"
            fi
        done
        return 1
    fi
    
    log_success "All dependencies found"
}

# Generate TypeScript types
generate_typescript() {
    log_info "Generating TypeScript types..."
    
    local count=0
    
    # Generate types for all JSON schema files
    while IFS= read -r -d '' schema_file; do
        local rel_path="${schema_file#$SCHEMAS_DIR/}"
        local base_name=$(basename "$schema_file" .json)
        local dir_name=$(dirname "$rel_path")
        
        # Output file
        local out_file="$TS_OUT/${base_name}.ts"
        
        # Generate using json-schema-to-typescript
        json2ts "$schema_file" -o "$out_file" \
            --bannerComment "/**\n * Auto-generated from $rel_path\n * DO NOT EDIT - Regenerate with: ./tools/generate_types.sh\n */" \
            --declareExternallyReferenced \
            --style.singleQuote
        
        ((count++))
        log_success "Generated: ${base_name}.ts"
    done < <(find "$SCHEMAS_DIR" -name "*.json" -type f -print0)
    
    # Generate index.ts
    cat > "$TS_OUT/index.ts" << 'EOF'
/**
 * TarlaAnaliz Contracts - TypeScript Types
 * Auto-generated from JSON Schema
 * DO NOT EDIT
 */

// Shared types
export * from './geojson.v1';
export * from './address.v1';
export * from './money.v1';

// Enums
export * from './crop_type.enum.v1';
export * from './role.enum.v1';
export * from './mission_status.enum.v1';
export * from './analysis_type.enum.v1';
export * from './threat_type.enum.v1';
export * from './quarantine_decision.enum.v1';

// Core entities
export * from './field.v1';
export * from './mission.v1';
export * from './user.v1';
export * from './user_pii.v1';

// Edge entities
export * from './intake_manifest.v1';
export * from './edge_metadata.v1';
export * from './quarantine_event.v1';

// Worker entities
export * from './analysis_job.v1';
export * from './analysis_result.v1';

// Events
export * from './field_created.v1';
export * from './mission_assigned.v1';
export * from './analysis_completed.v1';

// Platform
export * from './pricing.v1';
export * from './payroll.v1';
export * from './layer_registry.v1';
EOF
    
    log_success "Generated $count TypeScript type files"
    log_info "TypeScript types: $TS_OUT/"
}

# Generate Python types
generate_python() {
    log_info "Generating Python types..."
    
    local count=0
    
    # Generate types for all JSON schema files
    while IFS= read -r -d '' schema_file; do
        local rel_path="${schema_file#$SCHEMAS_DIR/}"
        local base_name=$(basename "$schema_file" .json)
        local python_name=$(echo "$base_name" | sed 's/\./_/g' | sed 's/-/_/g')
        
        # Output file
        local out_file="$PY_OUT/${python_name}.py"
        
        # Generate using datamodel-code-generator
        datamodel-codegen \
            --input "$schema_file" \
            --output "$out_file" \
            --input-file-type jsonschema \
            --output-model-type pydantic_v2.BaseModel \
            --field-constraints \
            --use-standard-collections \
            --use-schema-description \
            --use-field-description \
            --snake-case-field \
            --target-python-version 3.11
        
        # Add header comment
        local temp_file=$(mktemp)
        {
            echo "# Auto-generated from $rel_path"
            echo "# DO NOT EDIT - Regenerate with: ./tools/generate_types.sh"
            echo ""
            cat "$out_file"
        } > "$temp_file"
        mv "$temp_file" "$out_file"
        
        ((count++))
        log_success "Generated: ${python_name}.py"
    done < <(find "$SCHEMAS_DIR" -name "*.json" -type f -print0)
    
    # Generate __init__.py
    cat > "$PY_OUT/__init__.py" << 'EOF'
"""
TarlaAnaliz Contracts - Python Types
Auto-generated from JSON Schema
DO NOT EDIT
"""

# Shared types
from .geojson_v1 import *
from .address_v1 import *
from .money_v1 import *

# Enums
from .crop_type_enum_v1 import *
from .role_enum_v1 import *
from .mission_status_enum_v1 import *
from .analysis_type_enum_v1 import *
from .threat_type_enum_v1 import *
from .quarantine_decision_enum_v1 import *

# Core entities
from .field_v1 import *
from .mission_v1 import *
from .user_v1 import *
from .user_pii_v1 import *

# Edge entities
from .intake_manifest_v1 import *
from .edge_metadata_v1 import *
from .quarantine_event_v1 import *

# Worker entities
from .analysis_job_v1 import *
from .analysis_result_v1 import *

# Events
from .field_created_v1 import *
from .mission_assigned_v1 import *
from .analysis_completed_v1 import *

# Platform
from .pricing_v1 import *
from .payroll_v1 import *
from .layer_registry_v1 import *

__all__ = [
    # Export all generated types
]
EOF
    
    log_success "Generated $count Python type files"
    log_info "Python types: $PY_OUT/"
}

# Main function
main() {
    echo ""
    log_info "TarlaAnaliz Type Generator"
    echo ""
    
    local generate_ts=true
    local generate_py=true
    
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --typescript|--ts)
                generate_py=false
                shift
                ;;
            --python|--py)
                generate_ts=false
                shift
                ;;
            --clean)
                clean_generated
                exit 0
                ;;
            --help|-h)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --typescript, --ts    Generate TypeScript types only"
                echo "  --python, --py        Generate Python types only"
                echo "  --clean               Clean generated files"
                echo "  --help, -h            Show this help"
                echo ""
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                echo "Use --help for usage information"
                exit 1
                ;;
        esac
    done
    
    # Check dependencies
    if ! check_dependencies; then
        log_error "Dependency check failed"
        exit 1
    fi
    
    # Setup directories
    setup_directories
    
    # Generate types
    if [ "$generate_ts" = true ]; then
        generate_typescript
    fi
    
    if [ "$generate_py" = true ]; then
        generate_python
    fi
    
    echo ""
    log_success "Type generation complete!"
    echo ""
    log_info "Generated types:"
    if [ "$generate_ts" = true ]; then
        echo "  - TypeScript: $TS_OUT/"
    fi
    if [ "$generate_py" = true ]; then
        echo "  - Python: $PY_OUT/"
    fi
    echo ""
    log_warning "Remember: Generated files should NOT be edited manually"
    echo ""
}

# Run main
main "$@"